from .check_armatures_have_named_bones import PreflightCheckArmaturesHaveNamedBones
from .check_scene_has_active_camera import PreflightCheckSceneHasActiveCamera
from .check_has_camera import PreflightCheckHasCamera

BLENDER_PREFLIGHT_CHECK_LIST = [
    PreflightCheckHasCamera, PreflightCheckSceneHasActiveCamera, PreflightCheckArmaturesHaveNamedBones]
